# Use the SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy the project files
COPY ["CustomKeyboardsWeb/CustomKeyboardsWeb.csproj", "../"]
COPY ["CustomKeyboardsWeb.Application/CustomKeyboardsWeb.Application.csproj", "CustomKeyboardsWeb.Application/"]
COPY ["CustomKeyboardsWeb.Core/CustomKeyboardsWeb.Core.csproj", "CustomKeyboardsWeb.Core/"]
COPY ["CustomKeyboardsWeb.Data/CustomKeyboardsWeb.Data.csproj", "CustomKeyboardsWeb.Data/"]
COPY ["CustomKeyboardsWeb.Domain/CustomKeyboardsWeb.Domain.csproj", "CustomKeyboardsWeb.Domain/"]
COPY ["CustomKeyboardsWeb.Infrastructure/CustomKeyboardsWeb.Infrastructure.csproj", "CustomKeyboardsWeb.Infrastructure/"]


# Copy the entire project into the container
COPY . .

# Build the project
WORKDIR "/src/CustomKeyboardsWeb"
RUN dotnet build "CustomKeyboardsWeb.csproj" -c Release -o /app/build

# Create a temporary image to run EF Core migrations
FROM build AS migration
WORKDIR "/src/CustomKeyboardsWeb"

# Apply EF Core migrations
RUN dotnet ef database update --project CustomKeyboardsWeb.Data --context ApplicationMySqlDbContext

# Publish the application
FROM build AS publish
RUN dotnet publish "CustomKeyboardsWeb.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Use the ASP.NET runtime image for the final stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app

# Copy the published application
COPY --from=publish /app/publish .

# Entry point for the application
ENTRYPOINT ["dotnet", "CustomKeyboardsWeb.dll"]
